# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: Docker@2
  inputs:
    containerRegistry: 'studyingsquirrels-dockerhub'
    repository: 'service'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

# - task: Maven@3
#   inputs:
#     mavenPomFile: 'pom.xml'
#     publishJUnitResults: false
#     javaHomeOption: 'JDKVersion'
#     jdkVersionOption: '1.11'
#     mavenVersionOption: 'Default'
#     mavenAuthenticateFeed: false
#     effectivePomSkip: false
#     # sonarQubeRunAnalysis: true
#     # sqMavenPluginVersionChoice: 'latest'
