# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        $timenow = Get-Date -Format "yyyy.MM.dd.HH.mm.ss"
        $shotSha = ${sourceVersion:0:7}
        $dockertag = "$timenow" + "$shotSha"
        Write-Host $dockertag
        Write-Host "##vso[task.setvariable variable=dockertag;]$dockertag"

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      publishJUnitResults: false
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: 1.11
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      # sonarQubeRunAnalysis: true
      # sqMavenPluginVersionChoice: 'latest'
  

  - task: ContainerBuild@0
    inputs:
      dockerRegistryServiceConnection: 'studyingsquirrels-dockerhub'
      repository: 'studyingsquirrels/service'
      Dockerfile: 'Dockerfile'
      tags: |
        $(dockertag)	
  
  # TODO PUSH INFRA